name: Build Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build-macos:
    name: macOS
    runs-on: macos-latest

    steps:
      - name: Checkout sdl3-2d-engine
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          depth: 

      - name: CMake build
        run: |
          cmake -S . -B build
          cmake --build build
